### PR TITLE
Made the indicator image programatically generated to allow a own image for each percent

### PR DESCRIPTION
**Pull request by vortex852456**
This ensures that the battery level can be much more easily recognized based on the icon.

I implemented this because I was irritated that the icon was showing "full" at 88 percent. I didn't want to hover to see if it's really full.

### CODE REVIEW

**Comment by vortex852456** [comment]
image

This are the generated indicator images. 0-3 are empty (transparent).

**Comment by vortex852456** [comment]
I added an commit to display an charging icon when the battery percentage is 0 and the charging-bool is true instead of the missing icon.

image

**Comment by andyvorld** [comment]
Color and code looks good, however I know some devices like my G403 signals charging even when the battery is not at 0. Perhaps drawing the charging overlay on the colored bar?

**Comment by vortex852456** [comment]
Thanks for your feedback.
Your idea is good so I implemented it with my last commit.

Tested with different percentages and noted that the background bar makes the icons barely visible when turning green: image
But in lower percentages its clearly visible: image

This is only an issue on dark mode. On light mode the icon is clearly visible on all percentages.

**Comment by andyvorld** [comment]
Made a rewrite to the code for v3, https://github.com/andyvorld/LGSTrayBattery/releases/tag/v3.0.0-rc.1
I did not integrate the programmatic battery percentage as I felt that the battery level readout arent that precise anyway and should be fine as is. I did increase the threshold of "Full" battery to be >=85%.

The new version also have integrated a charging status.

**Comment by andyvorld** [comment]
Please try https://github.com/andyvorld/LGSTrayBattery/releases/tag/v3.0.0-rc.2 instead, had a packaging bug the prevented the native manager from running.

**Pull request closed without merging**
